### ISSUE TITLE
[BUG] unable to fetch machine IP

### ISSUE THREAD

**Issue by muX1337** [GoToolSharing/htb-cli#111]
**Describe the bug**
It take a very long time(more than 5min) or never fetching the IP of a machine either started already or not.

**To Reproduce**
htb-cli -v start --machine Analysis

**Expected behavior**
Showing the IP at least after 1min depending on the network-connection

**Screenshots**
 htb-cli -v start --machine Analysis                                                                                                                                                    2024-01-21T17:49:13.068+0100    INFO    config/config.go:179    Loading configuration file...                                                                                                                                               2024-01-21T17:49:13.081+0100    INFO    config/config.go:185    Configuration successfully loaded                                                                                                                                           ⠋2024-01-21T17:49:13.085+0100   INFO    utils/utils.go:479      Sending an HTTP request
2024-01-21T17:49:13.485+0100    INFO    cmd/start.go:150        Start command executed
2024-01-21T17:49:13.485+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request                                                                                                                                                 2024-01-21T17:49:13.758+0100    INFO    utils/utils.go:100      Machine found                                                                                                                                                               ? The following machine was found : Analysis Yes                                                                                                                                                                                            2024-01-21T17:49:15.860+0100    INFO    cmd/start.go:29 Machine ID: 584                                                                                                                                                                     2024-01-21T17:49:15.860+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request                                                                                                                                                 ⠋2024-01-21T17:49:15.860+0100   INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T17:49:16.109+0100    INFO    cmd/start.go:53 Machine Type: release                                                                                                                                                               2024-01-21T17:49:16.178+0100    INFO    cmd/start.go:61 User subscription: vip                                                                                                                                                              2024-01-21T17:49:16.178+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request                                                                                                                                                 ⠋2024-01-21T17:49:17.728+0100   INFO    utils/utils.go:381      Sending an HTTP HTB request
⠋2024-01-21T17:49:24.044+0100   INFO    utils/utils.go:381      Sending an HTTP HTB request
....
⠋ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:55:37.270+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
⠸ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:55:43.598+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
⠦ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:55:49.876+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
⠇ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:55:56.131+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
...
⠋ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:59:00.059+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
⠸ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:59:06.353+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
⠴ Waiting for the machine to start in order to fetch the IP address (this might take a while).2024-01-21T17:59:12.625+0100      INFO    utils/utils.go:381      Sending an HTTP HTB request
⠏ Waiting for the machine to start in order to fetch the IP address (this might take a while).Timeout (10 min) ! Exiting

Timeout after 10min

A ping to this machine is already working before the 10min:
 ping 10.10.11.250                                                                    
PING 10.10.11.250 (10.10.11.250) 56(84) bytes of data.
64 bytes from 10.10.11.250: icmp_seq=1 ttl=127 time=45.6 ms
64 bytes from 10.10.11.250: icmp_seq=2 ttl=127 time=47.4 ms
64 bytes from 10.10.11.250: icmp_seq=3 ttl=127 time=46.3 ms

Info-Command stated machine as started as well:
 htb-cli -v info 
2024-01-21T18:00:23.857+0100    INFO    config/config.go:179    Loading configuration file...
2024-01-21T18:00:23.861+0100    INFO    config/config.go:185    Configuration successfully loaded
⠋2024-01-21T18:00:23.867+0100   INFO    utils/utils.go:479      Sending an HTTP request
? Do you want to check for active machine ? Yes
2024-01-21T18:00:26.430+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T18:00:26.680+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T18:00:26.928+0100    INFO    cmd/info.go:222 Active machine found !
? Would you like to extend the active machine time ? Remaining: 25h 48m 49s No
2024-01-21T18:00:37.752+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T18:00:38.238+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T18:00:38.571+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T18:00:38.898+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
Name       |OS        |Retired   |Difficulty   |Stars   |IP          |Status     |Last Reset       |Release
Analysis   |Windows   |No        |Hard         |4.1     |Undefined   |No flags   |6 hours before   |2024-01-20
2024-01-21T18:00:39.191+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request

2024-01-21T18:00:39.489+0100    INFO    utils/utils.go:381      Sending an HTTP HTB request
2024-01-21T18:00:39.811+0100    INFO    utils/utils.go:186      Username found

**Comment by QU35T-code** [comment]
Hey @muX1337,

I made a lot of fix in dev. Can you try using the dev version ?

go install github.com/GoToolSharing/htb-cli@dev

**Comment by QU35T-code** [comment]
#98

**Comment by muX1337** [comment]
Hi @QU35T-code ,
you are right and sorry forgott about that you've already mentioned it. Somehow I thought I've done it already after reading this on your documentation: go install github.com/GoToolSharing/htb-cli@latest

Starting and fetching machine is now faster than a blink but got another issue for the command "htb-cli info":
`error: invalid character '<' looking for beginning of value
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/GoToolSharing/htb-cli/cmd.fetchAndDisplayInfo({0x9254b6, 0x36}, {0x0?, 0x4?}, {0xc0002a3a78, 0x1, 0x0?}, {0x90c987, 0x8})
        /mnt/e/kali/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.5.2-0.20240121120356-896f5a4ad67a/cmd/info.go:89 +0x1214
github.com/GoToolSharing/htb-cli/cmd.coreInfoCmd({0xd68be0?, 0x90c98f?, 0x0?}, {0xd68be0?, 0x0?, 0x0?}, {0xd68be0?, 0x0?, 0x0?})
        /mnt/e/kali/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.5.2-0.20240121120356-896f5a4ad67a/cmd/info.go:199 +0x60c
github.com/GoToolSharing/htb-cli/cmd.glob..func3(0xc0001ca400?, {0x90ac47?, 0x4?, 0x90abe3?})
        /mnt/e/kali/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.5.2-0.20240121120356-896f5a4ad67a/cmd/info.go:396 +0x1bc
github.com/spf13/cobra.(*Command).execute(0xd31540, {0xd68be0, 0x0, 0x0})
        /mnt/e/kali/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x691
github.com/spf13/cobra.(*Command).ExecuteC(0xd31f40)
        /mnt/e/kali/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /mnt/e/kali/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/GoToolSharing/htb-cli/cmd.Execute()
        /mnt/e/kali/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.5.2-0.20240121120356-896f5a4ad67a/cmd/root.go:46 +0x1a
main.main()
        /mnt/e/kali/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.5.2-0.20240121120356-896f5a4ad67a/main.go:8 +0xf`

As long it is a dev-branch I don't open another ticket.

**Comment by QU35T-code** [comment]
No worries, thanks for the feedback. I recommend using the dev branch for the moment because it fixes a lot of bugs ;)
