### ISSUE TITLE
[BUG] Start release arena machine

### ISSUE THREAD

**Issue by QU35T-code** [GoToolSharing/htb-cli#119]
```bash
➜  ~ htb-cli start
No machine is running
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoToolSharing/htb-cli/cmd.coreStartCmd({0x0?, 0xc000015b60?}, {0xc000015b50?, 0x0?})
	/home/qu35t/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.6.0/cmd/start.go:164 +0xde8
github.com/GoToolSharing/htb-cli/cmd.glob..func11(0xc00013a900?, {0x94d178?, 0x4?, 0x94d114?})
	/home/qu35t/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.6.0/cmd/start.go:194 +0x3be
github.com/spf13/cobra.(*Command).execute(0xd99ee0, {0xdd04c0, 0x0, 0x0})
	/home/qu35t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x691
github.com/spf13/cobra.(*Command).ExecuteC(0xd99760)
	/home/qu35t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
	/home/qu35t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/GoToolSharing/htb-cli/cmd.Execute()
	/home/qu35t/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.6.0/cmd/root.go:46 +0x1a
main.main()
	/home/qu35t/go/pkg/mod/github.com/!go!tool!sharing/htb-cli@v1.6.0/main.go:8 +0xf
```

**Comment by qu35t-code** [comment]
Wednesday 10:30 AM
```bash
htb-cli start
Machine deployed to lab. Playing on the release arena server!
Target: 10.129.214.94
Time to spawn was 1.22 seconds !
```
