### ISSUE TITLE
[BUG] Additional flags and logger

### ISSUE THREAD

**Issue by QU35T-code** [GoToolSharing/htb-cli#80]
**To Reproduce**

Add a bad flag

```bash
❯ go run . submit -d 1 -m Sau -fsdsdskdkkj
Error: unknown shorthand flag: 'f' in -fsdsdskdkkj
Usage:
  htb-cli submit [flags]

Flags:
  -c, --challenge_name string   Challenge Name
  -d, --difficulty int          Difficulty
  -h, --help                    help for submit
  -m, --machine_name string     Machine Name

Global Flags:
  -b, --batch           Don't ask questions
  -p, --proxy string    Configure a URL for an HTTP proxy
  -v, --verbose count   Verbose level

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102c5118c]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x2, {0x102d3712b, 0x22})
	/Users/qu35t/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:330 +0x4c
go.uber.org/zap.(*Logger).Error(0x1031fac40?, {0x102d3712b?, 0x1400005a688?}, {0x14000235200, 0x1, 0x1})
	/Users/qu35t/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:261 +0x40
github.com/GoToolSharing/htb-cli/cmd.Execute()
	/Users/qu35t/Documents/Perso/htb-cli/cmd/root.go:33 +0x104
main.main()
	/Users/qu35t/Documents/Perso/htb-cli/main.go:8 +0x1c
exit status 2
```

**Comment by QU35T-code** [comment]
Fixed
